### ISSUE TITLE
Only some setup codes are working

### ISSUE THREAD

**Issue by af-multichannelsystems** [Inateck-Technology-Inc/csharp_sdk#6]
Hello,

for my application, I need to change a few settings. I thought using the official manual (https://files.inateck.com/BCST-42_Complete%20Manual_EN.pdf) would be the correct way, but I had a few problems when reading a few of these codes nonetheless. 
Is it possible that I must not change the keyboard language when trying to scan a few of those codes?
For example:
I changed the keyboard language to German, saved and exited the setup. 
Entered setup, scanned the code for "Auto Red Light Shut off Mode" - "5s". After saving and exiting the time was still at 2s.
The same happened already with switching to Bluetooth mode.

Additionally to that question, another one:
What could be the reasons that I can't connect to the scanner?
I reset it by scanning the code in the manual, and scanned the code to switch to Bluetooth mode.
The scanner flashes a blue light, which should indicate, that switching was successful.
Then when using !scan the scanner is actually found. But as soon as I try connecting to it, I get this output:

Message: {"mac":"AC:3B:00:23:E4:4A","msg":"scan","product":"lixin@ST-42","type":1}
Message: scan

!connect
Command: connect
没有找到 peripheral
device is None
ConnectResult: {"device_name":"","mac":"","product_name":"","status":1}
Auth result: 1

Do you have any idea what's wrong?
I already tried connecting to it via my phone and disconnecting(Forget Device). This changed nothing unfortunately apart from the light now flashing green instead of blue. (The device is likely still in Bluetooth mode as this also happens when connecting and disconnecting using the SDK)

I would be glad if you could help me out here.
Thanks in advance!

**Comment by af-multichannelsystems** [comment]
I found a mistake made by me.
Nonetheless, I still can't connect to the scanner.
Now with the message:

> !connect
> Command: connect
> Message: {"mac":"AC:3B:00:23:E4:4A","msg":"disconnect","product":"","type":2}
> Message: disconnect
> The operation is not supported: Characteristic not found for subscribe
> device is None
> ConnectResult: {"device_name":"","mac":"","product_name":"","status":1}
> Auth result: 1

or:

> !connect
> Command: connect
> Not connected
> device is None
> ConnectResult: {"device_name":"","mac":"","product_name":"","status":1}
> Auth result: 1

What could be the reasons for that?

With a new scanner I have the following issue:

I can now connect to a scanner, but as soon as I scan something, the scanner won't do anything anymore.
When I click on the scan-button, no light shines. And after a few minutes, the scanner disconnects.
Every other operation works as usual (setting the volume/getting the software version/getting the battery percentage)

Could you give me a hint what could be my error?

**Comment by soSeven** [comment]
Hello, could you please let us know the model of the barcode scanner that is experiencing these issues? We would like to test this specific model.

**Comment by af-multichannelsystems** [comment]
The model is the BCST-42 
The SN of the new one is: 4C14XXL1
Of the other one: 4B22XXL1

**Comment by soSeven** [comment]
A new version has been released, and you can update your device to the latest version now

**Comment by af-multichannelsystems** [comment]
Thanks for updating!
Now I get the following error:

```
!connect
Command: connect
Connecting to Mac AC:3B:00:23:FF:7A
"{\"mac\":\"AC:3B:00:23:FF:7A\",\"msg\":\"disconnect\",\"product\":\"\",\"type\":2}"
Message: {"mac":"AC:3B:00:23:FF:7A","msg":"disconnect","product":"","type":2}
Message: disconnect
The operation is not supported: Characteristic not found for subscribe
device is None
Device: {"device_name":"","mac":"","product_name":"","status":1}
```

It should work, if I reset the scanner to factory defaults and scan the code to set the scanner into bluetooth mode, right?

**Comment by soSeven** [comment]
## Bluetooth Mode

| Bluetooth Mode | Status Value | Status              | cmd                        |
| -------------- | ------------- | ------------------- | -------------------------- |
| Bluetooth Mode | 0             | HID Mode            | {"flag": 1007, "value": 0} |
| Bluetooth Mode | 1             | SPP Mode            | {"flag": 1007, "value": 1} |
| Bluetooth Mode | 2             | GATT Mode           | {"flag": 1007, "value": 2} |
| Bluetooth Mode | 3             | Bluetooth Receiver Mode | {"flag": 1007, "value": 3} |


Hello, could you please specify which mode the scanner was in when the error occurred?

**Comment by af-multichannelsystems** [comment]
Hello,
the problem occurs when I'm trying to connect to the scanner. Is there a way to know, without connecting?
When using the SDK 2.0.1 with the Scanner 4B22XXL1 (The old one) I can get the settingsInfo:
<details>
<summary>Old scanner & old SDK</summary>
`{"info":[{"area":"1","name":"start_up_clean_cache","value":"0"},
{"area":"1","name":"auto_upload_cache","value":"0"},
{"area":"1","name":"only_read_specified_char","value":"0"},
{"area":"1","name":"factory_aging_mode","value":"0"},
{"area":"1","name":"factory_test_mode","value":"0"},
{"area":"1","name":"auto_off","value":"1"},
{"area":"1","name":"bt_mode_low","value":"0"},
{"area":"1","name":"read_inverse_color","value":"0"},
{"area":"2","name":"time_auto_off","value":"10"},
{"area":"3","name":"volume","value":"0"},
{"area":"4","name":"scan_mode","value":"2"},
{"area":"5","name":"time_continuous_mode","value":"10"},
{"area":"6","name":"auto_close_mode","value":"10"},
{"area":"7","name":"auto_sense_distan","value":"3"},
{"area":"8","name":"hide_front_byte","value":"0"},
{"area":"9","name":"hide_back_byte","value":"0"},
{"area":"10","name":"keyboard_type","value":"0"},
{"area":"11","name":"codabar_on","value":"1"},
{"area":"11","name":"interleaved25_on","value":"1"},
{"area":"11","name":"matrix25_on","value":"0"},
{"area":"11","name":"standard25_on","value":"0"},
{"area":"11","name":"code39_on","value":"1"},
{"area":"11","name":"code93_on","value":"1"},
{"area":"11","name":"code128_on","value":"1"},
{"area":"11","name":"iata25_on","value":"0"},
{"area":"12","name":"ean_8_on","value":"1"},
{"area":"12","name":"ean_13_on","value":"1"},
{"area":"12","name":"upc_e0_on","value":"1"},
{"area":"12","name":"chinese_post_on","value":"0"},
{"area":"12","name":"msi_on","value":"0"},
{"area":"12","name":"upc_a_on","value":"1"},
{"area":"12","name":"upc_e1_on","value":"0"},
{"area":"12","name":"code11_on","value":"0"},
{"area":"13","name":"upc_e_output","value":"1"},
{"area":"13","name":"code39_all_asci_on","value":"0"},
{"area":"13","name":"code39_start_stop_on","value":"0"},
{"area":"13","name":"matrix25_send_check","value":"0"},
{"area":"13","name":"upc_a_output","value":"0"},
{"area":"13","name":"codabar_start_stop_on","value":"1"},
{"area":"13","name":"standard25_send_check","value":"0"},
{"area":"13","name":"iata25_send_check","value":"0"},
{"area":"14","name":"ean_8_send_check","value":"1"},
{"area":"14","name":"code11_send_check","value":"1"},
{"area":"14","name":"upc_a_send_check","value":"1"},
{"area":"14","name":"upc_e_send_check","value":"1"},
{"area":"14","name":"msi_send_check","value":"1"},
{"area":"14","name":"ean_13_send_check","value":"1"},
{"area":"14","name":"code39_check_status","value":"0"},
{"area":"15","name":"vehicle_id_on","value":"0"},
{"area":"15","name":"suffix_add_enter","value":"1"},
{"area":"15","name":"code39_to_code32","value":"0"},
{"area":"15","name":"barcode_id_on","value":"0"},
{"area":"15","name":"custom_prefix_on","value":"1"},
{"area":"15","name":"custom_suffix_on","value":"1"},
{"area":"15","name":"usps_fedex","value":"1"},
{"area":"15","name":"code32_output_a","value":"0"},
{"area":"16","name":"data_transmission_speed","value":"0"},
{"area":"17","name":"specific_character1","value":"255"},
{"area":"18","name":"specific_character2","value":"255"},
{"area":"19","name":"specific_character3","value":"255"},
{"area":"20","name":"specific_character4","value":"255"},
{"area":"21","name":"specific_character5","value":"255"},
{"area":"22","name":"specific_character6","value":"255"},
{"area":"23","name":"delete_character","value":"0"},
{"area":"24","name":"gsreplace_char","value":"255"},
{"area":"25","name":"motor_swing_grade","value":"15"},
{"area":"25","name":"aztec_on","value":"0"},
{"area":"25","name":"maxicode_on","value":"0"},
{"area":"25","name":"dclick_upload_flag","value":"1"},
{"area":"25","name":"rss14_composite_on","value":"1"},
{"area":"26","name":"vat_type","value":"0"},
{"area":"26","name":"hanxin_on","value":"0"},
{"area":"26","name":"hanxin_read_phase","value":"0"},
{"area":"26","name":"security_level","value":"1"},
{"area":"26","name":"qrcode_read_phase","value":"0"},
{"area":"27","name":"gsreplace_char_on","value":"0"},
{"area":"27","name":"datamatrix_on","value":"1"},
{"area":"27","name":"datamatrix_read_multi","value":"0"},
{"area":"27","name":"output_char_type","value":"2"},
{"area":"27","name":"datamatrix_read_phase","value":"0"},
{"area":"28","name":"positioning_lamp_control","value":"0"},
{"area":"28","name":"lighting_lamp_control","value":"0"},
{"area":"28","name":"qrcode_on","value":"1"},
{"area":"28","name":"qrcode_read_more_code","value":"0"},
{"area":"28","name":"scan_head_upgrade_status","value":"0"},
{"area":"29","name":"serial_upgrade_scan_head_on","value":"0"},
{"area":"29","name":"pdf417_on","value":"1"},
{"area":"29","name":"vat_auto_output","value":"0"},
{"area":"29","name":"pdf417_read_more_code","value":"0"},
{"area":"29","name":"pdf417_read_phase","value":"0"},
{"area":"29","name":"iso_8859_on","value":"1"},
{"area":"30","name":"ean_8_extend_ean_13","value":"0"},
{"area":"30","name":"telepen_check","value":"0"},
{"area":"30","name":"plessey_on","value":"0"},
{"area":"30","name":"diacritic_on","value":"0"},
{"area":"30","name":"telepen_on","value":"0"},
{"area":"30","name":"repeat_data_check_on","value":"0"},
{"area":"30","name":"plessey_check","value":"0"},
{"area":"30","name":"addition_must_read","value":"0"},
{"area":"31","name":"bt_mode_high","value":"0"},
{"area":"31","name":"bracket_induction","value":"1"},
{"area":"31","name":"wireless_mode","value":"1"},
{"area":"31","name":"output_date","value":"0"},
{"area":"31","name":"shake_intensity","value":"0"},
{"area":"31","name":"output_time","value":"0"},
{"area":"31","name":"symb_128_on","value":"0"},
{"area":"31","name":"position_light_twinkle","value":"1"},
{"area":"32","name":"shake_reminder","value":"1"},
{"area":"32","name":"gs1_128","value":"1"},
{"area":"32","name":"ean_13_to_isbn","value":"0"},
{"area":"32","name":"chnpt_checksum_on","value":"0"},
{"area":"32","name":"chnpt_send_check","value":"1"},
{"area":"32","name":"shortcut_key_on","value":"0"},
{"area":"32","name":"gs_output","value":"0"},
{"area":"32","name":"ean_13_to_issn","value":"0"},
{"area":"33","name":"capslock","value":"1"},
{"area":"33","name":"country_board","value":"1"},
{"area":"34","name":"all_tow_code","value":"0"},
{"area":"34","name":"inventory_mode","value":"0"},
{"area":"34","name":"customized_func_on","value":"0"},
{"area":"34","name":"rss_14_on","value":"1"},
{"area":"34","name":"subfix_add_tab","value":"0"},
{"area":"34","name":"aim_id_on","value":"0"},
{"area":"35","name":"iata25_checksum_on","value":"0"},
{"area":"35","name":"code11_checksum_on","value":"0"},
{"area":"35","name":"upc_a_out_sn","value":"1"},
{"area":"35","name":"standard25_checksum_on","value":"0"},
{"area":"35","name":"matrix25_checksum_on","value":"0"},
{"area":"35","name":"msi_checksum_on","value":"1"},
{"area":"36","name":"ean_2","value":"0"},
{"area":"36","name":"add_hyphen","value":"0"},
{"area":"36","name":"letter_case","value":"0"},
{"area":"36","name":"hide_special_start_symbol","value":"0"},
{"area":"36","name":"upce_to_upca_check","value":"0"},
{"area":"36","name":"ignore_short_bar","value":"1"},
{"area":"36","name":"ean_5","value":"0"}],"status":0}
`
</details>
With the old scanner 4B22XXL1 and the new SDK, settingInfo puts this out:

<details>
<summary>Old scanner & new SDK</summary>
`
{"info":[{"flag":1012,"name":"auto_off","value":1},
{"flag":1015,"name":"start_up_clean_cache","value":0},
{"flag":1016,"name":"auto_upload_cache","value":0},
{"flag":1017,"name":"factory_Aging_Mode","value":0},
{"flag":1018,"name":"factory_Test_Mode","value":0},
{"flag":1007,"name":"BT_mode","value":0},
{"flag":1019,"name":"only_Read_Specified_Char","value":0},
{"flag":1020,"name":"read_Inverse_Color","value":0},
{"flag":1021,"name":"time_auto_off","value":10},
{"flag":1001,"name":"volume","value":0},
{"flag":1006,"name":"scan_mode","value":2},
{"flag":1022,"name":"time_continuous_mode","value":10},
{"flag":1023,"name":"auto_close_mode_time","value":10},
{"flag":1024,"name":"auto_sense_distance","value":3},
{"flag":1025,"name":"hide_front_byte","value":0},
{"flag":1026,"name":"hide_back_byte","value":0},
{"flag":2001,"name":"codabar_on","value":1},
{"flag":2002,"name":"iata25_on","value":0},
{"flag":2003,"name":"interleaved25_on","value":1},
{"flag":2004,"name":"matrix25_on","value":0},
{"flag":2005,"name":"standard25_on","value":0},
{"flag":2006,"name":"code39_on","value":1},
{"flag":2007,"name":"code93_on","value":1},
{"flag":2008,"name":"code128_on","value":1},
{"flag":2009,"name":"EAN_8_on","value":1},
{"flag":2010,"name":"EAN_13_on","value":1},
{"flag":2011,"name":"UPC_A_on","value":1},
{"flag":2012,"name":"UPC_E0_On","value":1},
{"flag":2013,"name":"MSI_on","value":0},
{"flag":2014,"name":"code11_on","value":0},
{"flag":2015,"name":"Chinese_post_on","value":0},
{"flag":2016,"name":"UPC_E1_On","value":0},
{"flag":3001,"name":"codabar_start_stop_on","value":1},
{"flag":3002,"name":"code39_start_stop_on","value":0},
{"flag":3003,"name":"code39_all_ascii_on","value":0},
{"flag":3004,"name":"UPC_A_output_0","value":0},
{"flag":3005,"name":"UPC_E_output_01","value":1},
{"flag":3006,"name":"iata25_send_check","value":0},
{"flag":3007,"name":"matrix25_send_check","value":0},
{"flag":3008,"name":"standard25_send_check","value":0},
{"flag":3009,"name":"code39_check_status","value":0},
{"flag":3010,"name":"EAN_8_send_check","value":1},
{"flag":3011,"name":"EAN_13_send_check","value":1},
{"flag":3012,"name":"UPC_A_send_check","value":1},
{"flag":3013,"name":"UPC_E_send_check","value":1},
{"flag":3014,"name":"code11_send_check","value":1},
{"flag":3015,"name":"MSI_send_check","value":1},
{"flag":1027,"name":"barcode_id_on","value":0},
{"flag":1028,"name":"suffix_add_enter","value":1},
{"flag":1029,"name":"custom_prefix_on","value":1},
{"flag":1030,"name":"custom_suffix_on","value":1},
{"flag":3016,"name":"vehicle_ID_On","value":0},
{"flag":3017,"name":"code39_to_code32","value":0},
{"flag":3018,"name":"code32_Output_A","value":0},
{"flag":3019,"name":"USPS_On","value":1},
{"flag":1031,"name":"data_transmit_interval","value":0},
{"flag":1064,"name":"specific_char1","value":255},
{"flag":1065,"name":"specific_char2","value":255},
{"flag":1066,"name":"specific_char3","value":255},
{"flag":1067,"name":"specific_char4","value":255},
{"flag":1068,"name":"specific_char5","value":255},
{"flag":1069,"name":"specific_char6","value":255},
{"flag":1033,"name":"delete_char_operation","value":0},
{"flag":1034,"name":"GS_Replace_Char","value":255},
{"flag":1014,"name":"d_click_upload_flag","value":1},
{"flag":1036,"name":"security_level","value":1},
{"flag":1037,"name":"output_char_type","value":2},
{"flag":1038,"name":"GS_Replace_Char_on","value":0},
{"flag":1042,"name":"diacritic_on","value":0},
{"flag":3030,"name":"ean8_extend_ean13","value":0},
{"flag":1043,"name":"repeat_data_check_on","value":0},
{"flag":1045,"name":"wireless_mode","value":1},
{"flag":1010,"name":"output_time","value":0},
{"flag":1009,"name":"output_date","value":0},
{"flag":1046,"name":"position_light_twinkle","value":1},
{"flag":3031,"name":"symb_128_on","value":0},
{"flag":3032,"name":"EAN13_to_ISBN","value":0},
{"flag":3033,"name":"EAN13_to_ISSN","value":0},
{"flag":3034,"name":"Chnpt_checksum_on","value":0},
{"flag":3035,"name":"Chnpt_send_check","value":1},
{"flag":2024,"name":"GS1_128","value":1},
{"flag":3036,"name":"GS_OUTPUT","value":0},
{"flag":1053,"name":"customized_func_on","value":1},
{"flag":1048,"name":"shortcut_Key_On","value":0},
{"flag":1005,"name":"country","value":1},
{"flag":1051,"name":"caps_lock_key_control","value":1},
{"flag":1013,"name":"inventory_mode","value":0},
{"flag":1002,"name":"shake_Reminder","value":0},
{"flag":1055,"name":"suffix_add_tab","value":0},
{"flag":3039,"name":"iata25_checksum_on","value":0},
{"flag":3040,"name":"matrix25_checksum_on","value":0},
{"flag":3041,"name":"standard25_checksum_on","value":0},
{"flag":3042,"name":"UPC_A_Out_SN","value":1},
{"flag":3043,"name":"code11_checksum_on","value":0},
{"flag":3044,"name":"MSI_checksum_on","value":1},
{"flag":3045,"name":"EAN_2","value":0},
{"flag":3046,"name":"EAN_5","value":0},
{"flag":3047,"name":"UPCEtoUPCA_check","value":0},
{"flag":3048,"name":"ignore_Short_Bar","value":1},
{"flag":1008,"name":"letter_Case","value":0},
{"flag":1056,"name":"add_Hyphen","value":0},
{"flag":1057,"name":"hide_Special_Start_Symbol","value":0}],"status":0}
`
</details>
--> HID Mode


When using the new Scanner (4C14XXL1) with the new SDK this happens:

<details>
  <summary>new Scanner & new SDK</summary>
  
`!connect
Command: connect
Connecting to Mac AA:3B:00:23:FF:7A
"{\"mac\":\"AA:3B:00:23:FF:7A\",\"msg\":\"disconnect\",\"product\":\"\",\"type\":2}"
Message: {"mac":"AA:3B:00:23:FF:7A","msg":"disconnect","product":"","type":2}
Message: disconnect
The operation is not supported: Characteristic not found for subscribe
device is None
Device: {"device_name":"","mac":"","product_name":"","status":1}`
 
</details>

With the new Scanner and the old SDK this happens:

<details>
  <summary>new Scanner & new SDK</summary>
  
`!connect
Command: connect
Message: {"mac":"AA:3B:00:23:FF:7A","msg":"disconnect","product":"","type":2}
Message: disconnect
The operation is not supported: Characteristic not found for subscribe
device is None
ConnectResult: {"device_name":"","mac":"","product_name":"","status":1}
Auth result: 1`
 
</details>


A colleague seemingly just found out, that using the Code of the BCST-4**3** to set the Scanner into GATT Mode now works. 
Does the SDK only work in GATT Mode? If so, why do the old scanners seem to work just fine when using the Bluetooth mode in the paper manual sent along with the scanner?

**Comment by soSeven** [comment]
Hello,The device works well in HID mode. I tested the BSCT-42 in HID mode and did not encounter the issue you mentioned. Could you kindly check your firmware version? My current firmware version is V4.1.7 (C) COPYRIGHT Inateck.

**Comment by af-multichannelsystems** [comment]
Hello,
I used the command !software. This resulted in the following outputs:
the new scanner (4C14XXL1) has the version: 4.1.4
the old one (4B22XXL1) has the version: 4.1.2

Everything works fine when using the GATT-Mode... The Barcode in the manual probably didn't set the mode to GATT...




Another thing I just discovered is:
When I'm connected and use the "!connect"-command again, the following message appears:
`!connect
Command: connect
Connecting to Mac AB:3B:00:23:FF:D7
Error { code: HRESULT(0x80000013), message: "The object has been closed." }
Error { code: HRESULT(0x80000013), message: "The object has been closed." }
Device: {"device_name":"","mac":"","product_name":"","status":1}`

After this appeared, nothing works anymore. I have to use !disconnect and !connect again to be able to communicate with the scanner again. 
Would it be possible for you to fix that?

**Comment by af-multichannelsystems** [comment]
Another question:

Which device type do I use?
The ST21 that you used in your demo? Or the ST42?
And will I run into trouble when using a wrong device? I would like to set the suffix from the code for example. But I fear that me using the wrong device will render the device unusable.

**Comment by soSeven** [comment]
> Another question:
> 
> Which device type do I use? The ST21 that you used in your demo? Or the ST42? And will I run into trouble when using a wrong device? I would like to set the suffix from the code for example. But I fear that me using the wrong device will render the device unusable.


Hello,I am using the BCST42, and I have corrected the errors in the example. Please note that the settings may vary depending on the specific device, so it's important to use the correct device for configuration. Additionally, the prefix and suffix functionality is not yet supported by the current SDK and will be available in the next version update.

**Comment by soSeven** [comment]
> Hello, I used the command !software. This resulted in the following outputs: the new scanner (4C14XXL1) has the version: 4.1.4 the old one (4B22XXL1) has the version: 4.1.2
> 
> Everything works fine when using the GATT-Mode... The Barcode in the manual probably didn't set the mode to GATT...
> 
> Another thing I just discovered is: When I'm connected and use the "!connect"-command again, the following message appears: `!connect Command: connect Connecting to Mac AB:3B:00:23:FF:D7 Error { code: HRESULT(0x80000013), message: "The object has been closed." } Error { code: HRESULT(0x80000013), message: "The object has been closed." } Device: {"device_name":"","mac":"","product_name":"","status":1}`
> 
> After this appeared, nothing works anymore. I have to use !disconnect and !connect again to be able to communicate with the scanner again. Would it be possible for you to fix that?

Hello,I have tested this issue and was unable to reproduce it. Could you please update the SDK and check if the problem persists? If the issue still occurs, could you let me know which operating system you are using?

**Comment by af-multichannelsystems** [comment]
The Problem persists. I just tested whether the problem has existed in previous versions. It also existed in version 2.0.1
I'm on:

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎29.‎07.‎2024
OS build	19045.4894
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by soSeven** [comment]
We have updated the SDK and documentation. You can try using the new SDK to resolve this issue.

[https://docs.inateck.com/scanner-sdk-en/](https://docs.inateck.com/scanner-sdk-en/)
